/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.3.0/userguide/multi_project_builds.html in the Gradle documentation.
 */

rootProject.name = "WildCommons"

include("v1_8_R3")
include("v_12_R1")
include("v1_9_R2")
include("WildCommons-Core")
